version: 0.2

phases:
  install:
    commands:
      # Yarn installation
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
      - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
      - sudo apt-get -y update
      - apt-get install -y yarn
      # Installing serverless globally
      - yarn global add serverless
      - yarn -v
      # Installing react and serverless dependencies
      - yarn install
      - ls -al
      - pwd
      - cd api && yarn install
      - cd ../app && npm install && yarn build
      - cd ..
      - mkdir api/react
      - ls -al
      - cd app/build && cp -r * ../../api/react
      - ls -al
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - api/*
    - api/*/*
    - infrastructure/*
    - code-build/*
