AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: beta-fire-one-page-app-bucket
  BetaFireLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonSESFullAccess
  BetaFireFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 'BetaFireFunction'
      Handler: index.handler
      Runtime: nodejs8.10
      Code:
        S3Bucket: 'beta-fire-deployment-bucket'
        S3Key: 'app.zip'
      Role:
        Fn::GetAtt:
          - BetaFireLambdaRole
          - Arn
