AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: beta-fire-one-page-app-bucket
  BetaFireFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Code:
        - S3Bucket: 'beta-fire-deployment-bucket'
        - S3Key: 'app.zip'
      Events:
        RootEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
